"use client";
import {useEffect,useRef} from "react";
import type PhaserType from "phaser";
export type WorldPlace={id:string;name:string;building:string;path:string;x:number;y:number;locked:boolean};
export default function PhaserCareerWorld({places,onFocus,onEnter,onHint}:{places:WorldPlace[];onFocus:(id:string)=>void;onEnter:(id:string)=>void;onHint:(text:string)=>void}){
  const host=useRef<HTMLDivElement>(null),callbacks=useRef({onFocus,onEnter,onHint});callbacks.current={onFocus,onEnter,onHint};
  useEffect(()=>{if(!host.current)return;let game:PhaserType.Game|undefined,cancelled=false;void import("phaser").then(({default:Phaser})=>{if(cancelled||!host.current)return;const worldW=1600,worldH=1000;
    class CareerTown extends Phaser.Scene{player!:PhaserType.Physics.Arcade.Sprite;cursors!:PhaserType.Types.Input.Keyboard.CursorKeys;keys!:Record<string,PhaserType.Input.Keyboard.Key>;nearest:WorldPlace|null=null;lastHint="";
      preload(){this.load.image("career-town","/assets/pixel/career-town-v1.webp")}
      makePerson(key:string,shirt:number,step=false){const g=this.make.graphics({x:0,y:0},false);g.fillStyle(0x111a17,.35).fillEllipse(16,37,25,7);g.fillStyle(0x263746).fillRect(step?8:9,27,6,9).fillRect(step?19:17,27,6,9);g.fillStyle(shirt).fillRect(7,15,20,15);g.lineStyle(2,0x203029).strokeRect(7,15,20,15);g.fillStyle(0xd9ad87).fillRect(10,6,15,11);g.fillStyle(0x252d29).fillRect(8,2,19,7);g.generateTexture(key,34,42);g.destroy()}
      create(){this.physics.world.setBounds(0,0,worldW,worldH);this.cameras.main.setBounds(0,0,worldW,worldH);this.add.image(worldW/2,worldH/2,"career-town").setDisplaySize(worldW,worldH);this.makePerson("player-idle",0x739e91);this.makePerson("player-step",0x88b4a6,true);this.makePerson("npc-blue",0x6e879f);this.makePerson("npc-gold",0xb98d55,true);this.player=this.physics.add.sprite(800,550,"player-idle").setCollideWorldBounds(true).setDepth(20).setBodySize(20,22).setOffset(7,17);
        [[0,0,1600,34],[0,966,1600,34],[0,0,34,1000],[1566,0,34,1000],[210,90,260,145],[1030,80,300,155],[1080,430,300,160],[180,410,250,150],[590,690,300,150]].forEach(([x,y,w,h])=>{const wall=this.add.rectangle(x+w/2,y+h/2,w,h,0,0);this.physics.add.existing(wall,true);this.physics.add.collider(this.player,wall)});
        [[520,360,710,430],[830,610,1060,670],[460,650,600,790],[980,290,1250,320]].forEach((r,i)=>{const npc=this.physics.add.sprite(r[0],r[1],i%2?"npc-gold":"npc-blue").setDepth(18);this.tweens.add({targets:npc,x:r[2],y:r[3],duration:4500+i*800,yoyo:true,repeat:-1,ease:"Sine.inOut",onYoyo:()=>npc.setFlipX(!npc.flipX),onRepeat:()=>npc.setFlipX(!npc.flipX)})});
        places.forEach(p=>{const x=p.x/100*worldW,y=p.y/100*worldH;const ring=this.add.circle(x,y,34,p.locked?0x8a615c:0xe4c66c,.13).setStrokeStyle(3,p.locked?0x9d7671:0xe4c66c,.8).setDepth(12);this.tweens.add({targets:ring,scale:1.16,alpha:.45,duration:1000,yoyo:true,repeat:-1});const label=this.add.text(x,y-48,p.locked?`${p.name} · 未开放`:`${p.name} · E进入`,{fontFamily:"sans-serif",fontSize:"15px",color:p.locked?"#d3aaa6":"#fff1ba",backgroundColor:"#101a16dd",padding:{x:7,y:4}}).setOrigin(.5).setDepth(25).setInteractive({useHandCursor:true});label.on("pointerdown",()=>{callbacks.current.onFocus(p.id);this.physics.moveTo(this.player,x,y+52,210)})});
        this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys("W,A,S,D,E") as Record<string,PhaserType.Input.Keyboard.Key>;this.input.keyboard!.on("keydown-E",()=>{if(!this.nearest)return;if(this.nearest.locked){callbacks.current.onHint("该区域尚未开放：先完成一次能力迁移");return}callbacks.current.onEnter(this.nearest.id)});this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.setZoom(.92);this.cameras.main.fadeIn(350,9,16,13)}
      update(){const body=this.player.body as PhaserType.Physics.Arcade.Body,left=this.cursors.left.isDown||this.keys.A.isDown,right=this.cursors.right.isDown||this.keys.D.isDown,up=this.cursors.up.isDown||this.keys.W.isDown,down=this.cursors.down.isDown||this.keys.S.isDown;body.setVelocity(0);if(left)body.setVelocityX(-190);if(right)body.setVelocityX(190);if(up)body.setVelocityY(-190);if(down)body.setVelocityY(190);body.velocity.normalize().scale(190);this.player.setFlipX(body.velocity.x<0).setTexture(body.speed>0&&Math.floor(this.time.now/170)%2?"player-step":"player-idle");let best:WorldPlace|null=null,dist=Infinity;for(const p of places){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,p.x/100*worldW,p.y/100*worldH);if(d<dist){dist=d;best=p}}this.nearest=dist<120?best:null;const hint=this.nearest?`按 E 进入：${this.nearest.building}`:"WASD / 方向键移动 · 靠近地点互动";if(hint!==this.lastHint){this.lastHint=hint;callbacks.current.onHint(hint)}}}
    game=new Phaser.Game({type:Phaser.AUTO,parent:host.current!,backgroundColor:"#15231d",pixelArt:true,roundPixels:true,physics:{default:"arcade",arcade:{debug:false}},scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},scene:CareerTown})});return()=>{cancelled=true;game?.destroy(true)}},[places]);
  return <div className="phaser-world" ref={host} aria-label="可探索职业像素小镇"/>;
}
