export type Alignment="malicious"|"benevolent"|"pragmatic";
export type DialogueIntentType="ask_information"|"verify_claim"|"negotiate_scope"|"confirm_credit"|"refuse_request"|"delay_decision"|"seek_empathy"|"flatter"|"threaten"|"document_evidence"|"expose_inconsistency"|"seek_alliance"|"accept_condition"|"exit_relationship"|"unknown";
export type EndingType="success"|"partial"|"failure"|"exit";

export interface NPCDefinition{ id:string;name:string;role:string;alignment:Alignment;primaryMotive:string;moralBoundary:string[];publicPersona:string;privateStrategy:string;canBeRedeemed:boolean;usesDeception:boolean;usesPowerPressure:boolean;retaliationPolicy:"never"|"indirect"|"proportional"|"aggressive";immutableTraits:string[];mutableTraits:string[];knownFacts:string[];hiddenFacts:string[];unknownFacts:string[];dialogueConstraints:string[];dialogueStyleId:string }
export interface StoryBeat{ id:string;title:string;description:string;unlockWhen:{stageAtLeast?:number;requiresFacts?:string[];requiresEvidence?:string[]};skippable?:boolean }
export interface MissionEnding{ id:string;title:string;type:EndingType;description:string;requirements:{stageAtLeast:number;facts?:string[];evidence?:string[];intent?:DialogueIntentType} }
export interface MissionDefinition{ id:string;title:string;npcIds:string[];immutablePremise:string;playerObjectives:string[];requiredStoryBeats:StoryBeat[];optionalStoryBeats:StoryBeat[];triggerConditions:string[];hiddenInformation:Record<string,string>;evidenceItems:{id:string;title:string;proves:string;source:string}[];allowedEndings:MissionEnding[];forbiddenChanges:string[];successConditions:string[];failureConditions:string[] }
export interface MissionRuntimeState{missionId:string;currentMissionStage:number;status:"active"|"completed"|"failed"|"exited";completedBeats:string[];optionalBeats:string[];discoveredFacts:string[];playerEvidence:string[];pastChoices:DialogueIntentType[];endingId?:string;turn:number}
export interface NPCRelationshipState{npcId:string;trust:number;respect:number;caution:number;resentment:number;powerGap:number;informationGap:number;playerDependencies:string[];npcDependencies:string[]}
export interface PlayerDialogueIntent{type:DialogueIntentType;confidence:number;target?:string;claim?:string;evidenceRefs:string[];rawText:string}
export interface NPCDecision{responseStrategy:"inform"|"deflect"|"probe"|"pressure"|"bargain"|"concede"|"withdraw"|"support";disclosureLevel:0|1|2|3;deceptionMode:"none"|"omit"|"misdirect"|"false_claim";pressureLevel:0|1|2|3;concessionLevel:0|1|2|3;emotionalTone:"calm"|"warm"|"guarded"|"defensive"|"cold"|"pressuring";nextTriggerSuggestion?:string;reactionTags:string[]}
export interface DialogueResponse{npcId:string;line:string;strategy:NPCDecision["responseStrategy"];reactionTags:string[];memorySummary:string;revealedFactIds:string[];mode:"ai"|"mock"|"fallback"}
export interface MissionTransitionResult{previousStage:number;nextStage:number;newlyCompletedBeats:string[];newlyDiscoveredFacts:string[];newEvidence:string[];relationshipDelta:Partial<Pick<NPCRelationshipState,"trust"|"respect"|"caution"|"resentment"|"powerGap"|"informationGap">>;resourceDelta:{time:number;energy:number;information:number};endingId?:string;blockedReasons:string[]}
export interface DialogueStyle{id:string;sentenceLength:"short"|"medium"|"mixed";register:string;habits:string[];forbidden:string[]}
